# Generated by Django 3.0.7 on 2020-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='descrption',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
