# Generated by Django 3.0.7 on 2020-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_descrption'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
