# Generated by Django 3.0.7 on 2020-06-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200618_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
