# Generated by Django 3.0.7 on 2020-06-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
